# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('languages', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('projectLink', models.CharField(max_length=300)),
                ('averageRating', models.FloatField()),
            ],
        ),
    ]
