# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reviewDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
