# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200607_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
