# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200608_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reviewDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 9, 29, 742344, tzinfo=utc)),
        ),
    ]
