# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-09 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200609_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
