# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-09 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200609_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('reviewDate', models.DateTimeField(default=datetime.datetime(2020, 6, 9, 1, 32, 43, 882811, tzinfo=utc))),
                ('languages', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('projectLink', models.CharField(max_length=300)),
                ('averageRating', models.FloatField(default=0)),
            ],
        ),
    ]
