# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-09 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reviewDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 1, 34, 57, 169920, tzinfo=utc)),
        ),
    ]
