# Generated by Django 3.0.7 on 2020-10-26 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201026_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reviewDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 9, 30, 13, 494962, tzinfo=utc)),
        ),
    ]
